- name: collect
  hosts: ords_nodes
  serial: 1

  tasks:
    - name: fetch url-mapping
      fetch:
        src: /Users/uhellstr/rest/ordsconfig/ords/url-mapping.xml
        dest: ./url-mapping.xml
        flat: yes
